# Generated by Django 5.0.6 on 2024-06-14 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarketingFunctions', '0002_specialoffer_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketingreport',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='trendanalysis',
            name='restaurant',
        ),
        migrations.DeleteModel(
            name='CustomerData',
        ),
        migrations.DeleteModel(
            name='MarketingReport',
        ),
        migrations.DeleteModel(
            name='TrendAnalysis',
        ),
    ]
