# Generated by Django 5.0.6 on 2024-06-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketingFunctions', '0005_alter_promotion_promotion_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='promotion_type',
            field=models.CharField(choices=[('discount', 'Rabatt'), ('special_item', 'Gericht außerhalb der Karte'), ('loyalty_points', 'Treuepunkte')], max_length=20),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='LoyaltyProgram',
        ),
    ]
